package com.acidglow.magiclibrary.config;

import com.acidglow.magiclibrary.MagicLibrary;
import com.acidglow.magiclibrary.MagicLibraryConfig;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import net.minecraft.core.Holder;
import net.minecraft.core.HolderLookup;
import net.minecraft.resources.Identifier;
import net.minecraft.world.entity.ai.attributes.Attributes;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.enchantment.Enchantment;
import net.minecraft.world.item.enchantment.EnchantmentEffectComponents;
import net.neoforged.fml.loading.FMLPaths;
import org.jspecify.annotations.Nullable;

public final class EnchantCapConfigLoader {
    private enum ItemApplicability {
        WEAPON,
        TOOL,
        ARMOR,
        RANGED,
        FISHING,
        MOVEMENT,
        SHIELD,
        MIXED,
        UNKNOWN
    }

    private enum DetectedEffectType {
        ATTACK_SPEED,
        WEAPON_DAMAGE,
        ARMOR_PROTECTION,
        RANGED_DAMAGE,
        NONE
    }

    public record EnchantCapRule(boolean canAmplify, int levelCap) {
        public EnchantCapRule {
            levelCap = Math.max(1, levelCap);
        }

        public static EnchantCapRule disabled() {
            return new EnchantCapRule(false, 1);
        }
    }

    private record ParsedCapEntry(Identifier enchantmentId, EnchantCapRule rule) {}

    private record ConfigEntry(EnchantCapRule rule, List<String> comments) {}

    private record AutoGeneratedEntry(
        EnchantCapRule rule,
        int modMaxLevel,
        String heuristicName,
        String reason,
        boolean reviewRecommended
    ) {}

    private static final Path CONFIG_DIRECTORY = FMLPaths.CONFIGDIR.get().resolve(MagicLibrary.MODID);
    private static final Path ENCHANT_CAPS_FILE = CONFIG_DIRECTORY.resolve("enchant_caps.toml");

    private static final ItemStack SAMPLE_HELMET = new ItemStack(Items.DIAMOND_HELMET);
    private static final ItemStack SAMPLE_CHESTPLATE = new ItemStack(Items.DIAMOND_CHESTPLATE);
    private static final ItemStack SAMPLE_LEGGINGS = new ItemStack(Items.DIAMOND_LEGGINGS);
    private static final ItemStack SAMPLE_BOOTS = new ItemStack(Items.DIAMOND_BOOTS);
    private static final ItemStack SAMPLE_ELYTRA = new ItemStack(Items.ELYTRA);
    private static final ItemStack SAMPLE_SHIELD = new ItemStack(Items.SHIELD);
    private static final ItemStack SAMPLE_SWORD = new ItemStack(Items.DIAMOND_SWORD);
    private static final ItemStack SAMPLE_AXE = new ItemStack(Items.DIAMOND_AXE);
    private static final ItemStack SAMPLE_PICKAXE = new ItemStack(Items.DIAMOND_PICKAXE);
    private static final ItemStack SAMPLE_SHOVEL = new ItemStack(Items.DIAMOND_SHOVEL);
    private static final ItemStack SAMPLE_HOE = new ItemStack(Items.DIAMOND_HOE);
    private static final ItemStack SAMPLE_BOW = new ItemStack(Items.BOW);
    private static final ItemStack SAMPLE_CROSSBOW = new ItemStack(Items.CROSSBOW);
    private static final ItemStack SAMPLE_TRIDENT = new ItemStack(Items.TRIDENT);
    private static final ItemStack SAMPLE_FISHING_ROD = new ItemStack(Items.FISHING_ROD);

    private static Map<Identifier, EnchantCapRule> cachedEnchantCaps = Map.of();

    private EnchantCapConfigLoader() {
    }

    public static synchronized void initialize() {
        reload(MagicLibraryConfig.getLegacyAmplificationRuleEntriesForMigration());
    }

    public static synchronized void reload() {
        reload(MagicLibraryConfig.getLegacyAmplificationRuleEntriesForMigration());
    }

    public static synchronized void reload(List<String> legacyRuleEntries) {
        ensureConfigFileExists(legacyRuleEntries);
        cachedEnchantCaps = Map.copyOf(parseEnchantCapsFile());
    }

    public static synchronized boolean existsOnDisk() {
        return Files.exists(ENCHANT_CAPS_FILE);
    }

    public static synchronized @Nullable EnchantCapRule getEnchantCapRule(Identifier enchantmentId) {
        return cachedEnchantCaps.get(enchantmentId);
    }

    public static synchronized void appendMissingEnchantEntries(HolderLookup.RegistryLookup<Enchantment> enchantLookup) {
        ensureConfigFileExists(MagicLibraryConfig.getLegacyAmplificationRuleEntriesForMigration());

        Map<Identifier, EnchantCapRule> existingEntries = parseEnchantCapsFile();
        Map<String, LinkedHashMap<String, AutoGeneratedEntry>> missingEntries = new LinkedHashMap<>();

        enchantLookup.listElements().forEach(holder -> {
            Identifier enchantmentId = holder.unwrapKey().map(key -> key.identifier()).orElse(null);
            if (enchantmentId == null || existingEntries.containsKey(enchantmentId)) {
                return;
            }

            AutoGeneratedEntry defaultEntry = classifyDiscoveredEnchant(holder, enchantmentId);
            missingEntries.computeIfAbsent(enchantmentId.getNamespace(), ignored -> new LinkedHashMap<>()).put(enchantmentId.getPath(), defaultEntry);
        });

        if (missingEntries.isEmpty()) {
            cachedEnchantCaps = Map.copyOf(existingEntries);
            return;
        }

        List<String> lines;
        try {
            lines = Files.exists(ENCHANT_CAPS_FILE)
                ? new ArrayList<>(Files.readAllLines(ENCHANT_CAPS_FILE, StandardCharsets.UTF_8))
                : new ArrayList<>();
        } catch (IOException exception) {
            throw new IllegalStateException("Failed to read enchant caps config: " + ENCHANT_CAPS_FILE, exception);
        }

        for (Map.Entry<String, LinkedHashMap<String, AutoGeneratedEntry>> namespaceEntry : missingEntries.entrySet()) {
            appendNamespaceEntries(lines, namespaceEntry.getKey(), namespaceEntry.getValue());
        }

        try {
            Files.write(ENCHANT_CAPS_FILE, lines, StandardCharsets.UTF_8);
        } catch (IOException exception) {
            throw new IllegalStateException("Failed to update enchant caps config: " + ENCHANT_CAPS_FILE, exception);
        }

        cachedEnchantCaps = Map.copyOf(parseEnchantCapsFile());
    }

    private static AutoGeneratedEntry classifyDiscoveredEnchant(Holder.Reference<Enchantment> enchantment, Identifier enchantmentId) {
        int modMaxLevel = Math.max(1, enchantment.value().getMaxLevel());
        ItemApplicability applicability = analyzeItemApplicability(enchantment);
        DetectedEffectType detectedEffectType = detectEnchantEffectType(enchantment, applicability);

        if (detectedEffectType == DetectedEffectType.ATTACK_SPEED) {
            return new AutoGeneratedEntry(
                new EnchantCapRule(true, 50),
                modMaxLevel,
                "attack_speed",
                "item applicability + attack speed effect",
                false
            );
        }
        if (detectedEffectType == DetectedEffectType.WEAPON_DAMAGE) {
            return new AutoGeneratedEntry(
                new EnchantCapRule(true, 100),
                modMaxLevel,
                applicability == ItemApplicability.RANGED ? "ranged_damage" : "weapon_damage",
                applicability == ItemApplicability.RANGED ? "ranged applicability + damage effect" : "weapon applicability + damage effect",
                false
            );
        }
        if (detectedEffectType == DetectedEffectType.ARMOR_PROTECTION) {
            return new AutoGeneratedEntry(
                new EnchantCapRule(true, 10),
                modMaxLevel,
                "armor_protection",
                applicability == ItemApplicability.SHIELD ? "shield applicability + protection effect" : "armor applicability + protection effect",
                false
            );
        }
        if (detectedEffectType == DetectedEffectType.RANGED_DAMAGE) {
            return new AutoGeneratedEntry(
                new EnchantCapRule(true, 100),
                modMaxLevel,
                "ranged_damage",
                "ranged applicability + projectile damage effect",
                false
            );
        }

        if (isLifeStealEnchant(enchantmentId)) {
            return new AutoGeneratedEntry(
                new EnchantCapRule(true, 5),
                modMaxLevel,
                "life_steal",
                "life-steal keyword fallback",
                false
            );
        }

        if (isSpeedLikeWeaponEnchant(applicability, enchantmentId)) {
            return new AutoGeneratedEntry(
                new EnchantCapRule(true, 50),
                modMaxLevel,
                "attack_speed",
                "weapon applicability + speed-like keyword fallback",
                false
            );
        }
        if (isSpeedLikeToolEnchant(applicability, enchantmentId)) {
            return new AutoGeneratedEntry(
                new EnchantCapRule(true, 100),
                modMaxLevel,
                "mining_speed",
                "tool applicability + speed-like keyword fallback",
                false
            );
        }
        if (isSpeedLikeMovementEnchant(applicability, enchantmentId)) {
            return new AutoGeneratedEntry(
                new EnchantCapRule(true, modMaxLevel),
                modMaxLevel,
                "movement_related",
                "movement applicability + speed-like keyword fallback; using mod max level",
                true
            );
        }
        if (isFallbackRangedDamageEnchant(applicability, enchantmentId)) {
            return new AutoGeneratedEntry(
                new EnchantCapRule(true, 100),
                modMaxLevel,
                "ranged_damage",
                "ranged applicability + keyword fallback",
                false
            );
        }
        if (isFallbackArmorProtectionEnchant(applicability, enchantmentId)) {
            return new AutoGeneratedEntry(
                new EnchantCapRule(true, 10),
                modMaxLevel,
                "armor_protection",
                applicability == ItemApplicability.SHIELD ? "shield applicability + defense keyword fallback" : "armor applicability + protection keyword fallback",
                false
            );
        }
        if (isFallbackWeaponDamageEnchant(applicability, enchantmentId)) {
            return new AutoGeneratedEntry(
                new EnchantCapRule(true, 100),
                modMaxLevel,
                "weapon_damage",
                "weapon applicability + damage keyword fallback",
                false
            );
        }

        if (modMaxLevel == 1 || isClearlyBinarySpecialEnchant(enchantment, enchantmentId, applicability)) {
            return new AutoGeneratedEntry(
                EnchantCapRule.disabled(),
                modMaxLevel,
                "binary/special",
                modMaxLevel == 1 ? "single-level enchant; disabled by default" : "clear binary or toggle-like effect detected",
                modMaxLevel > 1
            );
        }

        return new AutoGeneratedEntry(
            new EnchantCapRule(true, modMaxLevel),
            modMaxLevel,
            "unknown_multi_level",
            getUnknownFallbackReason(applicability),
            true
        );
    }

    private static ItemApplicability analyzeItemApplicability(Holder.Reference<Enchantment> enchantment) {
        boolean weapon = appliesToWeapons(enchantment);
        boolean tool = appliesToTools(enchantment);
        boolean armor = appliesToArmor(enchantment);
        boolean ranged = appliesToRanged(enchantment);
        boolean fishing = enchantment.value().canEnchant(SAMPLE_FISHING_ROD);
        boolean movement = enchantment.value().canEnchant(SAMPLE_ELYTRA);
        boolean shield = enchantment.value().canEnchant(SAMPLE_SHIELD);

        int groupCount = countTrue(weapon, tool, armor, ranged, fishing, movement, shield);
        if (groupCount == 0) {
            return ItemApplicability.UNKNOWN;
        }
        if (groupCount > 1) {
            if (movement && !weapon && !tool && !ranged && !fishing && !shield) {
                return ItemApplicability.MOVEMENT;
            }
            if (movement && armor && !weapon && !tool && !ranged && !fishing && !shield) {
                return ItemApplicability.MOVEMENT;
            }
            if (shield && !weapon && !tool && !armor && !ranged && !fishing && !movement) {
                return ItemApplicability.SHIELD;
            }
            return ItemApplicability.MIXED;
        }
        if (weapon) {
            return ItemApplicability.WEAPON;
        }
        if (tool) {
            return ItemApplicability.TOOL;
        }
        if (armor) {
            return ItemApplicability.ARMOR;
        }
        if (ranged) {
            return ItemApplicability.RANGED;
        }
        if (fishing) {
            return ItemApplicability.FISHING;
        }
        if (movement) {
            return ItemApplicability.MOVEMENT;
        }
        return ItemApplicability.SHIELD;
    }

    private static DetectedEffectType detectEnchantEffectType(Holder.Reference<Enchantment> enchantment, ItemApplicability applicability) {
        if (hasAttributeEffect(enchantment, Attributes.ATTACK_SPEED)) {
            return applicability == ItemApplicability.WEAPON ? DetectedEffectType.ATTACK_SPEED : DetectedEffectType.NONE;
        }
        if (hasAttributeEffect(enchantment, Attributes.ATTACK_DAMAGE)
            || hasValueEffects(enchantment, EnchantmentEffectComponents.DAMAGE, EnchantmentEffectComponents.SMASH_DAMAGE_PER_FALLEN_BLOCK)) {
            if (applicability == ItemApplicability.RANGED) {
                return DetectedEffectType.RANGED_DAMAGE;
            }
            if (applicability == ItemApplicability.WEAPON) {
                return DetectedEffectType.WEAPON_DAMAGE;
            }
        }
        if (hasValueEffects(enchantment, EnchantmentEffectComponents.DAMAGE_PROTECTION, EnchantmentEffectComponents.ARMOR_EFFECTIVENESS)
            || hasUnitEffect(enchantment, EnchantmentEffectComponents.DAMAGE_IMMUNITY)) {
            if (applicability == ItemApplicability.ARMOR || applicability == ItemApplicability.SHIELD) {
                return DetectedEffectType.ARMOR_PROTECTION;
            }
        }
        return DetectedEffectType.NONE;
    }

    private static boolean isLifeStealEnchant(Identifier enchantmentId) {
        String path = enchantmentId.getPath().toLowerCase(Locale.ROOT);
        return containsKeyword(path, "lifesteal", "life_steal", "vampir", "leech", "drain");
    }

    private static boolean isClearlyBinarySpecialEnchant(
        Holder.Reference<Enchantment> enchantment,
        Identifier enchantmentId,
        ItemApplicability applicability
    ) {
        if (hasUnitEffect(enchantment, EnchantmentEffectComponents.PREVENT_EQUIPMENT_DROP, EnchantmentEffectComponents.PREVENT_ARMOR_CHANGE)) {
            return true;
        }

        String path = enchantmentId.getPath().toLowerCase(Locale.ROOT);
        return applicability != ItemApplicability.MOVEMENT && containsKeyword(
            path,
            "silk_touch",
            "silktouch",
            "channeling",
            "soulbound",
            "soul_bound",
            "binding",
            "vanishing",
            "curse"
        );
    }

    private static boolean isSpeedLikeWeaponEnchant(ItemApplicability applicability, Identifier enchantmentId) {
        return applicability == ItemApplicability.WEAPON && hasSpeedLikeKeyword(enchantmentId);
    }

    private static boolean isSpeedLikeToolEnchant(ItemApplicability applicability, Identifier enchantmentId) {
        return applicability == ItemApplicability.TOOL && (hasSpeedLikeKeyword(enchantmentId) || hasMiningKeyword(enchantmentId));
    }

    private static boolean isSpeedLikeMovementEnchant(ItemApplicability applicability, Identifier enchantmentId) {
        return (applicability == ItemApplicability.MOVEMENT || applicability == ItemApplicability.ARMOR) && hasSpeedLikeKeyword(enchantmentId);
    }

    private static boolean isFallbackRangedDamageEnchant(ItemApplicability applicability, Identifier enchantmentId) {
        return applicability == ItemApplicability.RANGED && hasRangedKeyword(enchantmentId);
    }

    private static boolean isFallbackArmorProtectionEnchant(ItemApplicability applicability, Identifier enchantmentId) {
        return (applicability == ItemApplicability.ARMOR || applicability == ItemApplicability.SHIELD) && hasProtectionKeyword(enchantmentId);
    }

    private static boolean isFallbackWeaponDamageEnchant(ItemApplicability applicability, Identifier enchantmentId) {
        return applicability == ItemApplicability.WEAPON && hasWeaponDamageKeyword(enchantmentId) && !isLifeStealEnchant(enchantmentId);
    }

    private static String getUnknownFallbackReason(ItemApplicability applicability) {
        return switch (applicability) {
            case WEAPON -> "weapon applicability but effect unclear; using mod max level";
            case TOOL -> "tool applicability but effect unclear; using mod max level";
            case ARMOR -> "armor applicability but effect unclear; using mod max level";
            case RANGED -> "ranged applicability but effect unclear; using mod max level";
            case FISHING -> "fishing applicability but effect unclear; using mod max level";
            case MOVEMENT -> "movement applicability but effect unclear; using mod max level";
            case SHIELD -> "shield applicability but effect unclear; using mod max level";
            case MIXED -> "mixed item applicability; using mod max level";
            case UNKNOWN -> "classification unclear; using mod max level";
        };
    }

    private static boolean hasSpeedLikeKeyword(Identifier enchantmentId) {
        String path = enchantmentId.getPath().toLowerCase(Locale.ROOT);
        return containsKeyword(path, "speed", "swiftness", "haste", "rapid", "quick", "frenzy");
    }

    private static boolean hasMiningKeyword(Identifier enchantmentId) {
        String path = enchantmentId.getPath().toLowerCase(Locale.ROOT);
        return containsKeyword(path, "efficiency", "mining", "miner", "dig", "excavat");
    }

    private static boolean hasProtectionKeyword(Identifier enchantmentId) {
        String path = enchantmentId.getPath().toLowerCase(Locale.ROOT);
        return containsKeyword(path, "protect", "protection", "guard", "ward", "resist");
    }

    private static boolean hasRangedKeyword(Identifier enchantmentId) {
        String path = enchantmentId.getPath().toLowerCase(Locale.ROOT);
        return containsKeyword(path, "arrow", "bow", "sniper", "pierce", "power", "projectile");
    }

    private static boolean hasWeaponDamageKeyword(Identifier enchantmentId) {
        String path = enchantmentId.getPath().toLowerCase(Locale.ROOT);
        return containsKeyword(path, "damage", "sharp", "smite", "bane", "slayer", "cleave", "strike", "impact", "brutal");
    }

    private static boolean hasAttributeEffect(Holder.Reference<Enchantment> enchantment, Holder<net.minecraft.world.entity.ai.attributes.Attribute> attribute) {
        return enchantment.value().getEffects(EnchantmentEffectComponents.ATTRIBUTES).stream().anyMatch(effect -> effect.attribute().equals(attribute));
    }

    @SafeVarargs
    private static boolean hasValueEffects(
        Holder.Reference<Enchantment> enchantment,
        net.minecraft.core.component.DataComponentType<List<net.minecraft.world.item.enchantment.ConditionalEffect<net.minecraft.world.item.enchantment.effects.EnchantmentValueEffect>>>... effectTypes
    ) {
        for (var effectType : effectTypes) {
            if (!enchantment.value().getEffects(effectType).isEmpty()) {
                return true;
            }
        }
        return false;
    }

    @SafeVarargs
    private static boolean hasUnitEffect(
        Holder.Reference<Enchantment> enchantment,
        net.minecraft.core.component.DataComponentType<?>... effectTypes
    ) {
        for (var effectType : effectTypes) {
            if (enchantment.value().effects().has(effectType)) {
                return true;
            }
        }
        return false;
    }

    private static boolean appliesToArmor(Holder.Reference<Enchantment> enchantment) {
        return enchantment.value().canEnchant(SAMPLE_HELMET)
            || enchantment.value().canEnchant(SAMPLE_CHESTPLATE)
            || enchantment.value().canEnchant(SAMPLE_LEGGINGS)
            || enchantment.value().canEnchant(SAMPLE_BOOTS);
    }

    private static boolean appliesToMovementItems(Holder.Reference<Enchantment> enchantment) {
        return enchantment.value().canEnchant(SAMPLE_BOOTS)
            || enchantment.value().canEnchant(SAMPLE_ELYTRA)
            || appliesToArmor(enchantment);
    }

    private static boolean appliesToWeapons(Holder.Reference<Enchantment> enchantment) {
        return enchantment.value().canEnchant(SAMPLE_SWORD)
            || enchantment.value().canEnchant(SAMPLE_AXE)
            || enchantment.value().canEnchant(SAMPLE_TRIDENT);
    }

    private static boolean appliesToTools(Holder.Reference<Enchantment> enchantment) {
        return enchantment.value().canEnchant(SAMPLE_PICKAXE)
            || enchantment.value().canEnchant(SAMPLE_SHOVEL)
            || enchantment.value().canEnchant(SAMPLE_HOE);
    }

    private static boolean appliesToRanged(Holder.Reference<Enchantment> enchantment) {
        return enchantment.value().canEnchant(SAMPLE_BOW)
            || enchantment.value().canEnchant(SAMPLE_CROSSBOW)
            || enchantment.value().canEnchant(SAMPLE_TRIDENT);
    }

    private static boolean containsKeyword(String value, String... keywords) {
        for (String keyword : keywords) {
            if (value.contains(keyword)) {
                return true;
            }
        }
        return false;
    }

    private static int countTrue(boolean... values) {
        int count = 0;
        for (boolean value : values) {
            if (value) {
                count++;
            }
        }
        return count;
    }

    private static void ensureConfigFileExists(List<String> legacyRuleEntries) {
        try {
            Files.createDirectories(CONFIG_DIRECTORY);
            if (!Files.exists(ENCHANT_CAPS_FILE)) {
                Files.writeString(ENCHANT_CAPS_FILE, buildDefaultFileContents(legacyRuleEntries), StandardCharsets.UTF_8);
            }
        } catch (IOException exception) {
            throw new IllegalStateException("Failed to initialize enchant caps config: " + ENCHANT_CAPS_FILE, exception);
        }
    }

    private static Map<Identifier, EnchantCapRule> parseEnchantCapsFile() {
        if (!Files.exists(ENCHANT_CAPS_FILE)) {
            return Map.of();
        }

        Map<Identifier, EnchantCapRule> parsed = new LinkedHashMap<>();
        String currentNamespace = "";
        try {
            for (String rawLine : Files.readAllLines(ENCHANT_CAPS_FILE, StandardCharsets.UTF_8)) {
                String line = stripComment(rawLine).trim();
                if (line.isEmpty()) {
                    continue;
                }

                if (isNamespaceHeader(line)) {
                    currentNamespace = line.substring(1, line.length() - 1).trim();
                    continue;
                }

                int splitIndex = line.indexOf('=');
                if (splitIndex <= 0 || currentNamespace.isEmpty()) {
                    continue;
                }

                String path = line.substring(0, splitIndex).trim();
                String valueToken = line.substring(splitIndex + 1).trim();
                if (path.isEmpty() || valueToken.isEmpty()) {
                    continue;
                }

                Identifier enchantmentId = Identifier.tryBuild(currentNamespace, path);
                EnchantCapRule rule = parseRuleToken(valueToken);
                if (enchantmentId != null && rule != null) {
                    parsed.put(enchantmentId, rule);
                }
            }
        } catch (IOException exception) {
            throw new IllegalStateException("Failed to read enchant caps config: " + ENCHANT_CAPS_FILE, exception);
        }

        return parsed;
    }

    private static String buildDefaultFileContents(List<String> legacyRuleEntries) {
        StringBuilder builder = new StringBuilder();
        builder.append("# Magic Library enchant amplification caps").append(System.lineSeparator());
        builder.append("# Effective cap = min(global softCap in magiclibrary-common.toml, per-enchant cap here)").append(System.lineSeparator());
        builder.append("# Use \"disabled\" to block Tome amplification for an enchant").append(System.lineSeparator());
        builder.append(System.lineSeparator());

        boolean firstSection = true;
        for (Map.Entry<String, LinkedHashMap<String, ConfigEntry>> namespaceEntry : buildDefaultGroupedCaps(legacyRuleEntries).entrySet()) {
            if (!firstSection) {
                builder.append(System.lineSeparator());
            }
            firstSection = false;
            builder.append("[").append(namespaceEntry.getKey()).append("]").append(System.lineSeparator()).append(System.lineSeparator());
            boolean firstEntry = true;
            for (Map.Entry<String, ConfigEntry> enchantEntry : namespaceEntry.getValue().entrySet()) {
                if (!firstEntry) {
                    builder.append(System.lineSeparator());
                }
                firstEntry = false;
                appendCommentBlock(builder, enchantEntry.getValue().comments());
                builder.append(enchantEntry.getKey()).append(" = ").append(formatRuleValue(enchantEntry.getValue().rule())).append(System.lineSeparator());
            }
        }
        return builder.toString();
    }

    private static Map<String, LinkedHashMap<String, ConfigEntry>> buildDefaultGroupedCaps(List<String> legacyRuleEntries) {
        Map<Identifier, ConfigEntry> mergedEntries = new LinkedHashMap<>();
        mergeDefaultEntries(mergedEntries, MagicLibraryConfig.getDefaultAmplificationEnchantRuleEntries());
        mergeLegacyEntries(mergedEntries, legacyRuleEntries);

        Map<String, LinkedHashMap<String, ConfigEntry>> groupedCaps = new LinkedHashMap<>();
        for (Map.Entry<Identifier, ConfigEntry> entry : mergedEntries.entrySet()) {
            Identifier enchantmentId = entry.getKey();
            groupedCaps.computeIfAbsent(enchantmentId.getNamespace(), ignored -> new LinkedHashMap<>()).put(enchantmentId.getPath(), entry.getValue());
        }
        return groupedCaps;
    }

    private static void mergeDefaultEntries(Map<Identifier, ConfigEntry> target, List<String> rawEntries) {
        for (String rawEntry : rawEntries) {
            ParsedCapEntry parsedEntry = parseRawEntry(rawEntry);
            if (parsedEntry != null) {
                List<String> comments = parsedEntry.enchantmentId().getNamespace().equals("minecraft")
                    ? List.of("Vanilla enchant", "Magic Library default cap")
                    : List.of("Magic Library default cap");
                target.put(parsedEntry.enchantmentId(), new ConfigEntry(parsedEntry.rule(), comments));
            }
        }
    }

    private static void mergeLegacyEntries(Map<Identifier, ConfigEntry> target, List<String> rawEntries) {
        for (String rawEntry : rawEntries) {
            ParsedCapEntry parsedEntry = parseRawEntry(rawEntry);
            if (parsedEntry != null) {
                target.put(
                    parsedEntry.enchantmentId(),
                    new ConfigEntry(parsedEntry.rule(), List.of("Migrated from legacy magiclibrary-common.toml"))
                );
            }
        }
    }

    private static @Nullable ParsedCapEntry parseRawEntry(String rawEntry) {
        String entry = rawEntry == null ? "" : rawEntry.trim();
        if (entry.isEmpty()) {
            return null;
        }

        int splitIndex = entry.indexOf('=');
        if (splitIndex <= 0 || splitIndex >= entry.length() - 1) {
            return null;
        }

        Identifier enchantmentId = Identifier.tryParse(entry.substring(0, splitIndex).trim());
        EnchantCapRule rule = parseRuleToken(entry.substring(splitIndex + 1).trim());
        if (enchantmentId == null || rule == null) {
            return null;
        }
        return new ParsedCapEntry(enchantmentId, rule);
    }

    private static @Nullable EnchantCapRule parseRuleToken(String rawValueToken) {
        String valueToken = rawValueToken == null ? "" : rawValueToken.trim();
        if (valueToken.isEmpty()) {
            return null;
        }

        String normalizedToken = stripWrappingQuotes(valueToken).trim();
        if ("disabled".equalsIgnoreCase(normalizedToken)) {
            return EnchantCapRule.disabled();
        }

        try {
            int cap = Integer.parseInt(normalizedToken);
            if (cap < 1) {
                return null;
            }
            return new EnchantCapRule(true, cap);
        } catch (NumberFormatException ignored) {
            return null;
        }
    }

    private static void appendNamespaceEntries(List<String> lines, String namespace, LinkedHashMap<String, AutoGeneratedEntry> entries) {
        if (entries.isEmpty()) {
            return;
        }

        int sectionStart = findNamespaceSectionStart(lines, namespace);
        if (sectionStart < 0) {
            if (!lines.isEmpty() && !lines.getLast().isBlank()) {
                lines.add("");
            }
            lines.add("[" + namespace + "]");
            lines.add("");
            sectionStart = lines.size() - 2;
        }

        int insertIndex = findNamespaceInsertIndex(lines, sectionStart);
        for (Map.Entry<String, AutoGeneratedEntry> entry : entries.entrySet()) {
            if (insertIndex > sectionStart + 1 && !lines.get(insertIndex - 1).isBlank()) {
                lines.add(insertIndex++, "");
            }
            AutoGeneratedEntry autoEntry = entry.getValue();
            lines.add(insertIndex++, "# Auto-generated by Magic Library");
            lines.add(insertIndex++, "# Mod max level: " + autoEntry.modMaxLevel());
            lines.add(insertIndex++, "# Heuristic: " + autoEntry.heuristicName());
            lines.add(insertIndex++, "# Reason: " + autoEntry.reason());
            if (autoEntry.reviewRecommended()) {
                lines.add(insertIndex++, "# Review recommended");
            }
            lines.add(insertIndex++, entry.getKey() + " = " + formatRuleValue(autoEntry.rule()));
        }
    }

    private static int findNamespaceSectionStart(List<String> lines, String namespace) {
        String header = "[" + namespace + "]";
        for (int i = 0; i < lines.size(); i++) {
            if (header.equals(lines.get(i).trim())) {
                return i;
            }
        }
        return -1;
    }

    private static int findNamespaceInsertIndex(List<String> lines, int sectionStart) {
        int index = sectionStart + 1;
        while (index < lines.size() && !isNamespaceHeader(lines.get(index).trim())) {
            index++;
        }
        while (index > sectionStart + 1 && lines.get(index - 1).isBlank()) {
            index--;
        }
        return index;
    }

    private static boolean isNamespaceHeader(String line) {
        return line.startsWith("[") && line.endsWith("]");
    }

    private static void appendCommentBlock(StringBuilder builder, List<String> comments) {
        for (String comment : comments) {
            builder.append("# ").append(comment).append(System.lineSeparator());
        }
    }

    private static String formatRuleValue(EnchantCapRule rule) {
        if (!rule.canAmplify()) {
            return "\"disabled\"";
        }
        return Integer.toString(Math.max(1, rule.levelCap()));
    }

    private static String stripWrappingQuotes(String value) {
        if (value.length() >= 2 && value.startsWith("\"") && value.endsWith("\"")) {
            return value.substring(1, value.length() - 1);
        }
        return value;
    }

    private static String stripComment(String line) {
        int commentIndex = line.indexOf('#');
        if (commentIndex >= 0) {
            return line.substring(0, commentIndex);
        }
        return line;
    }
}
